version: '2.1'
services:

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: playlist-api/config
    restart: always

  eureka:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: playlist/eureka
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: playlist/gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  user-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: playlist/user-service
    restart: always
    depends_on:
      config:
        condition: service_healthy

  playlist-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: playlist/playlist-service
    restart: always
    depends_on:
      config:
        condition: service_healthy

  album-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: playlist/album-service
    restart: always
    depends_on:
      config:
        condition: service_healthy