
#spring.application.name = api-gateway
#server.port = 8090
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

#zuul.routes.user-service.path=/users/**
#zuul.routes.playlist-service.path=/playlists/**
#zuul.routes.album-service.path=/albums/**, /songs/**

spring:
  application:
    name: api-gateway

server:
  port: 8090


zuul:
  routes:
    user-service:
      path: /users/**
      stripPrefix: false
    notification-service:
      path: /notifications/**
      stripPrefix: false
    playlist:
      path: /playlists/**
      serviceId: playlist-service
      stripPrefix: false
    song:
      path: /songs/**
      serviceId: playlist-service
      stripPrefix: false
    album:
      path: /albums/**
      serviceId: playlist-service
      stripPrefix: false


  sensitiveHeaders: Cookie,Set-Cookie
  add-proxy-headers: true
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
eureka:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
    resource:
      jwt:
        key-value: jwt_secret_key


